settings:
  title: 'Status Page'
  url: 'https://status-page.eidam.dev' # used for Slack messages
  logo: logo-192x192.png # image in ./public/ folder
  daysInHistogram: 90 # number of days you want to display in histogram
  collectResponseTimes: true # collects avg response times from CRON locations

  allmonitorsOperational: 'All Systems Operational'
  notAllmonitorsOperational: 'Not All Systems Operational'
  monitorLabelOperational: 'Operational'
  monitorLabelNotOperational: 'Not Operational'
  monitorLabelNoData: 'No data'
  dayInHistogramNoData: 'No data'
  dayInHistogramOperational: 'All good'
  dayInHistogramNotOperational: ' incident(s)' # xx incident(s) recorded

monitors:
  - id: Jellyfin # unique identifier
    name: Jellyfin Movie Server
    description: 'Main Media Server.' # default=empty
    url: 'https://jfapp.xyz/' # URL to fetch
    method: GET # default=GET
    expectStatus: 200 # operational status, default=200
    linkable: true # allows the title to be a link, default=true

  - id: Requests
    name: Movie Requests
    description: 'Server For Requesting Movies'
    url: 'https://requests.jellyfinserver.xyz/'
    method: GET
    expectStatus: 200
    linkable: true # allows the title to be a link, default=true

  - id: Game Server Panel
    name: Game Server Panel
    description: 'Server Panel to Host Games'
    url: 'https://panel.beckerle.xyz/'
    method: GET
    expectStatus: 200
